[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

# RPC endpoints
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

# Etherscan API keys
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Gas settings
[profile.gas_reports]
enabled = true